### ISSUE TITLE
ERROR: Failed building wheel for hnswlib

### ISSUE THREAD

**Issue by dlazarou** [muellerberndt/micro-gpt#16]
i think this is common for other builds as well.

**Comment by muellerberndt** [comment]
What Python package is that related to?

**Comment by muellerberndt** [comment]
> What Python package is that related to?

Can one of you guys provide this info?

**Comment by leonardofmed** [comment]
> > What Python package is that related to?
> 
> Can one of you guys provide this info?

I believe that is related to chromadb:
```
Collecting mpmath>=0.19 (from sympy->torch>=1.6.0->sentence-transformers>=2.2.2->chromadb==0.3.11->-r requirements.txt (line 9))
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Building wheels for collected packages: hnswlib, sentence-transformers
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
  ```

**Comment by novaprod** [comment]
I had problems with pinecone and chromadb so i edited the code and added the JSON settings and i solved all of my problems ahaha

**Comment by dlazarou** [comment]
my python is 3.10, yes ,that is the package. I only have 3.7 and 3.10 but i think <3.8 doesn't work with GPT packages.

@novaprod where in the JSON settings?

**Comment by muellerberndt** [comment]
I just removed the chromadb package from requirements, users will need to install it manually if they choose to use ChromaDB.
