### ISSUE TITLE
model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by FiveTechSoft** [muellerberndt/micro-gpt#17]
I have provided the valid OpenAI key in .env but I guess it is not valid for gpt-4

what to use for 3.5 ? The model `gpt-3.5` does not exist

`gpt-3` also fails

I am subscribed to GPT4 but I guess the OpenAI keys I get are for 3.5 only.  Should we use a waitlist to get them ?

thanks

**Comment by FiveTechSoft** [comment]
Solved:

MODEL="gpt-3.5-turbo"

How to get the GPT4 keys ? thanks

**Comment by muellerberndt** [comment]
> I have provided the valid OpenAI key in .env but I guess it is not valid for gpt-4
> 
> what to use for 3.5 ? The model `gpt-3.5` does not exist
> 
> `gpt-3` also fails
> 
> I am subscribed to GPT4 but I guess the OpenAI keys I get are for 3.5 only. Should we use a waitlist to get them ?
> 
> thanks

Yep, you need to join the [waitlist](https://openai.com/waitlist/gpt-4-api) to get access to GPT-4.
