### ISSUE TITLE
"ERROR: Could not build wheels for hnswlib"

### ISSUE THREAD

**Issue by tdimino** [muellerberndt/micro-gpt#34]
Has anyone encountered this error when running, "pip install -r requirements.txt" for BabyAGI? I've tried to install hnswlib manually via its own repo, but still get the same message. 

I'm on a MacBook, by the by.

**Comment by muellerberndt** [comment]
Yep, it's an issue with building ChromaDB, see #16 (closing this as a duplicate).

**Comment by tdimino** [comment]
Worth mentioning that I posed the same question to ChatGPT (when installing on my Windows machine) and found a solution to the error.

> This error occurs when trying to build the hnswlib package, which is a dependency of the project you're working on. The error message indicates that the required Microsoft Visual C++ 14.0 or greater is missing from your system. This compiler is necessary for building the C++ extension of hnswlib.

To resolve this error, you need to install the Microsoft Visual C++ Build Tools. You can do this by following these steps:

    Go to the Microsoft Visual Studio website to download the Build Tools: https://visualstudio.microsoft.com/visual-cpp-build-tools/
    Click "Download Build Tools" and run the installer.
    In the installer, under "Workloads," select "C++ build tools."
    Make sure the following components are selected in the "Installation details" pane:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
        Windows 10 SDK
        C++ CMake tools for Windows
        C++ ATL for the latest v142 build tools (x86 & x64)
        C++ MFC for the latest v142 build tools (x86 & x64)
        C++/CLI support for v142 build tools (14.21)
        C++ Modules for the latest v142 build tools (x64/x86)
        Clang Compiler for Windows
        Windows Universal CRT SDK
        Windows 8.1 SDK
    Click "Install" and wait for the installation to complete.

After the installation is complete, you may need to restart your computer. Once the required components are installed, try building or installing the hnswlib package again, and the error should be `resolved.`

**Comment by tdimino** [comment]
I solved this, and successfully installed MicroGPT by cloning the hnswlib repo, then running "pip install -r requirements.txt" for it.
