### ISSUE TITLE
Getting a lot of timeouts

### ISSUE THREAD

**Issue by jwestonmoss** [muellerberndt/micro-gpt#46]
Getting a ton of these:

`/Retrying langchain.chat_models.openai.ChatOpenAI.completion_with_retry.<locals>._completion_with_retry in 1.0 seconds as it raised Timeout: Request timed out: HTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=60).`

Any thoughts on the cause?  It works occasionally.  But most of the time I keep getting these timeouts.

**Comment by muellerberndt** [comment]
It's a known issue, unfortunately the it requires a fix in ThinkGPT. I have [opened an issue](https://github.com/alaeddine-13/thinkgpt/issues/6), will try to get it fixed ASAP.

**Comment by muellerberndt** [comment]
I believe it should be fixed now. @jwestonmoss can you try installing thinkgpt-0.0.5 and pulling the latest commit:

```
pip install -U thinkgpt
git pull
```

Let me know if it fixes the issue for you.

**Comment by jwestonmoss** [comment]
Thanks for the response.  I assumed part of the solution was just increasing the minimum timeout, but it seemed that part was external as you pointed out.  I'll try that, thanks

**Comment by jwestonmoss** [comment]
That did seem to work, thanks
