### ISSUE TITLE
Pinecone Library is problematic

### ISSUE THREAD

**Issue by TheBarret** [muellerberndt/micro-gpt#8]
We can't get it to work, because Pinecone is currently over used.

We are met with this message:
"Due to extremely high demand, a waitlist is currently in place for new Starter (free) users"

**Comment by McFork** [comment]
Pinecone just crashes for me.

```
File "K:\micro-gpt\microgpt.py", line 49, in <module>
    memory = PineconeMemory()
  File "K:\micro-gpt\memory.py", line 26, in __init__
    if "microgpt" not in pinecone.list_indexes():
  File "[...]\Python310\site-packages\pinecone\manage.py", line 185, in list_indexes
    response = api_instance.list_indexes()
```

**Comment by estiens** [comment]
I just implemented a working implementation using postgres with pg_vector installed it's in a PR

**Comment by madbuda** [comment]
@estiens looks like I missed your PR, I added an option for redis https://github.com/muellerberndt/micro-gpt/pull/10

**Comment by muellerberndt** [comment]
Thanks for both your PRs! I'd say we merge both & let the user decide?

**Comment by muellerberndt** [comment]
@madbuda @estiens I ended up merging the Postgres PR and closing the Redis one... even though it would be cool to have Redis support, this PR didn't use vector store/similarity search, and the merge conflicts got too big as well. @madbuda if you want to have another go at is, look at [this](https://redis.io/docs/stack/search/reference/vectors/). It would very useful :)

**Comment by madbuda** [comment]
@muellerberndt I'll take a look and see what I can do

**Comment by muellerberndt** [comment]
We now have support for ChromaDB and Postgresq so I'm closing this issue.
